apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ga-exporter
  labels:
    k8s-app: ga-exporter
spec:
  selector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  namespaceSelector:
    matchNames:
    - default
    - monitoring
  endpoints:
  - port: web
    interval: 10s
